name: ml_conda_pycaret
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - streamlit
  - mlflow
  - xgboost
  - pip:
    - pycaret==3.2.0 