channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=22.3.1
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
  - xgboost==2.1.3
name: mlflow-env
